In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

In [ ]:
data = pd.read_csv('..\\data\\train.csv')
data.head()

,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,New_Price,Price
0,Maruti Wagon R LXI CNG,Mumbai,2010,72000,CNG,Manual,First,26.6 km/kg,998 CC,58.16 bhp,5.0,NaN,1.75
1,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,Diesel,Manual,First,19.67 kmpl,1582 CC,126.2 bhp,5.0,NaN,12.50
2,Honda Jazz V,Chennai,2011,46000,Petrol,Manual,First,18.2 kmpl,1199 CC,88.7 bhp,5.0,8.61 Lakh,4.50
3,Maruti Ertiga VDI,Chennai,2012,87000,Diesel,Manual,First,20.77 kmpl,1248 CC,88.76 bhp,7.0,NaN,6.00
4,Audi A4 New 2.0 TDI Multitronic,Coimbatore,2013,40670,Diesel,Automatic,Second,15.2 kmpl,1968 CC,140.8 bhp,5.0,NaN,17.74

In [3]:
data["Model"] = data["Name"].str.split()
data["Brand"] = data["Model"].str[0]
data.head()

,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,New_Price,Price,Model,Brand
0,Maruti Wagon R LXI CNG,Mumbai,2010,72000,CNG,Manual,First,26.6 km/kg,998 CC,58.16 bhp,5.0,NaN,1.75,"[Maruti, Wagon, R, LXI, CNG]",Maruti
1,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,Diesel,Manual,First,19.67 kmpl,1582 CC,126.2 bhp,5.0,NaN,12.50,"[Hyundai, Creta, 1.6, CRDi, SX, Option]",Hyundai
2,Honda Jazz V,Chennai,2011,46000,Petrol,Manual,First,18.2 kmpl,1199 CC,88.7 bhp,5.0,8.61 Lakh,4.50,"[Honda, Jazz, V]",Honda
3,Maruti Ertiga VDI,Chennai,2012,87000,Diesel,Manual,First,20.77 kmpl,1248 CC,88.76 bhp,7.0,NaN,6.00,"[Maruti, Ertiga, VDI]",Maruti
4,Audi A4 New 2.0 TDI Multitronic,Coimbatore,2013,40670,Diesel,Automatic,Second,15.2 kmpl,1968 CC,140.8 bhp,5.0,NaN,17.74,"[Audi, A4, New, 2.0, TDI, Multitronic]",Audi

In [4]:
data["Model"] = data["Model"].str[1:]
data.head()

,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,New_Price,Price,Model,Brand
0,Maruti Wagon R LXI CNG,Mumbai,2010,72000,CNG,Manual,First,26.6 km/kg,998 CC,58.16 bhp,5.0,NaN,1.75,"[Wagon, R, LXI, CNG]",Maruti
1,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,Diesel,Manual,First,19.67 kmpl,1582 CC,126.2 bhp,5.0,NaN,12.50,"[Creta, 1.6, CRDi, SX, Option]",Hyundai
2,Honda Jazz V,Chennai,2011,46000,Petrol,Manual,First,18.2 kmpl,1199 CC,88.7 bhp,5.0,8.61 Lakh,4.50,"[Jazz, V]",Honda
3,Maruti Ertiga VDI,Chennai,2012,87000,Diesel,Manual,First,20.77 kmpl,1248 CC,88.76 bhp,7.0,NaN,6.00,"[Ertiga, VDI]",Maruti
4,Audi A4 New 2.0 TDI Multitronic,Coimbatore,2013,40670,Diesel,Automatic,Second,15.2 kmpl,1968 CC,140.8 bhp,5.0,NaN,17.74,"[A4, New, 2.0, TDI, Multitronic]",Audi

In [5]:
data["Model"] = data["Model"].str.join(' ')
data.head()

,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,New_Price,Price,Model,Brand
0,Maruti Wagon R LXI CNG,Mumbai,2010,72000,CNG,Manual,First,26.6 km/kg,998 CC,58.16 bhp,5.0,NaN,1.75,Wagon R LXI CNG,Maruti
1,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,Diesel,Manual,First,19.67 kmpl,1582 CC,126.2 bhp,5.0,NaN,12.50,Creta 1.6 CRDi SX Option,Hyundai
2,Honda Jazz V,Chennai,2011,46000,Petrol,Manual,First,18.2 kmpl,1199 CC,88.7 bhp,5.0,8.61 Lakh,4.50,Jazz V,Honda
3,Maruti Ertiga VDI,Chennai,2012,87000,Diesel,Manual,First,20.77 kmpl,1248 CC,88.76 bhp,7.0,NaN,6.00,Ertiga VDI,Maruti
4,Audi A4 New 2.0 TDI Multitronic,Coimbatore,2013,40670,Diesel,Automatic,Second,15.2 kmpl,1968 CC,140.8 bhp,5.0,NaN,17.74,A4 New 2.0 TDI Multitronic,Audi

In [29]:
data = data.drop(["Name", "Location", "Engine", "Seats", "New_Price"], axis=1)
data.head()

,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Power,Price,Model,Brand
0,2010,72000,CNG,Manual,First,26.6 km/kg,58.16 bhp,1.75,Wagon R LXI CNG,Maruti
1,2015,41000,Diesel,Manual,First,19.67 kmpl,126.2 bhp,12.50,Creta 1.6 CRDi SX Option,Hyundai
2,2011,46000,Petrol,Manual,First,18.2 kmpl,88.7 bhp,4.50,Jazz V,Honda
3,2012,87000,Diesel,Manual,First,20.77 kmpl,88.76 bhp,6.00,Ertiga VDI,Maruti
4,2013,40670,Diesel,Automatic,Second,15.2 kmpl,140.8 bhp,17.74,A4 New 2.0 TDI Multitronic,Audi

In [30]:
data["Mileage"] = data["Mileage"].str.split()
data["Mileage"] = data["Mileage"].str[0]
data["Power"] = data["Power"].str.split()
data["Power"] = data["Power"].str[0]
data.head()

,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Power,Price,Model,Brand
0,2010,72000,CNG,Manual,First,26.6,58.16,1.75,Wagon R LXI CNG,Maruti
1,2015,41000,Diesel,Manual,First,19.67,126.2,12.50,Creta 1.6 CRDi SX Option,Hyundai
2,2011,46000,Petrol,Manual,First,18.2,88.7,4.50,Jazz V,Honda
3,2012,87000,Diesel,Manual,First,20.77,88.76,6.00,Ertiga VDI,Maruti
4,2013,40670,Diesel,Automatic,Second,15.2,140.8,17.74,A4 New 2.0 TDI Multitronic,Audi

In [31]:
data["Price"] = data["Price"]*929.9

In [32]:
data.head(20)

,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Power,Price,Model,Brand
0,2010,72000,CNG,Manual,First,26.6,58.16,1627.325,Wagon R LXI CNG,Maruti
1,2015,41000,Diesel,Manual,First,19.67,126.2,11623.750,Creta 1.6 CRDi SX Option,Hyundai
2,2011,46000,Petrol,Manual,First,18.2,88.7,4184.550,Jazz V,Honda
3,2012,87000,Diesel,Manual,First,20.77,88.76,5579.400,Ertiga VDI,Maruti
4,2013,40670,Diesel,Automatic,Second,15.2,140.8,16496.426,A4 New 2.0 TDI Multitronic,Audi
5,2012,75000,LPG,Manual,First,21.1,55.2,2185.265,EON LPG Era Plus Option,Hyundai
6,2013,86999,Diesel,Manual,First,23.08,63.1,3254.650,Micra Diesel XV,Nissan
7,2016,36000,Diesel,Automatic,First,11.36,171.5,16273.250,Innova Crysta 2.8 GX AT 8S,Toyota
8,2013,64430,Diesel,Manual,First,20.54,103.6,4835.480,Vento Diesel Comfortline,Volkswagen
9,2012,65932,Diesel,Manual,Second,22.3,74,1813.305,Indica Vista Quadrajet LS,Tata
10,2018,25692,Petrol,Manual,First,21.56,103.25,9252.505,Ciaz Zeta,Maruti
11,2012,60000,Petrol,Automatic,First,16.8,116.3,4175.251,City 1.5 V AT Sunroof,Honda
12,2015,64424,Diesel,Manual,First,25.2,74,5207.440,Swift VDI BSIV,Maruti
13,2014,72000,Diesel,Automatic,First,12.7,187.7,25107.300,Rover Range Rover 2.2L Pure,Land
14,2012,85000,Diesel,Automatic,Second,0.0,115,16273.250,Rover Freelander 2 TD4 SE,Land
15,2014,110000,Diesel,Manual,First,13.5,175.56,13948.500,Pajero Sport 4X4,Mitsubishi
16,2016,58950,Diesel,Manual,First,25.8,98.6,5021.460,Amaze S i-Dtech,Honda
17,2017,25000,Diesel,Manual,First,28.4,74,5570.101,Swift DDiS VDI,Maruti
18,2014,77469,Diesel,Manual,First,20.45,83.8,5895.566,Duster 85PS Diesel RxL Plus,Renault
19,2014,78500,Diesel,Automatic,First,14.84,167.62,26037.200,New C-Class C 220 CDI BE Avantgare,Mercedes-Benz

In [33]:
data["Brand"] = data["Brand"].str.upper()
data.head()

,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Power,Price,Model,Brand
0,2010,72000,CNG,Manual,First,26.6,58.16,1627.325,Wagon R LXI CNG,MARUTI
1,2015,41000,Diesel,Manual,First,19.67,126.2,11623.750,Creta 1.6 CRDi SX Option,HYUNDAI
2,2011,46000,Petrol,Manual,First,18.2,88.7,4184.550,Jazz V,HONDA
3,2012,87000,Diesel,Manual,First,20.77,88.76,5579.400,Ertiga VDI,MARUTI
4,2013,40670,Diesel,Automatic,Second,15.2,140.8,16496.426,A4 New 2.0 TDI Multitronic,AUDI

In [34]:
data["Model"] = data["Model"].str.upper()
data.head()

,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Power,Price,Model,Brand
0,2010,72000,CNG,Manual,First,26.6,58.16,1627.325,WAGON R LXI CNG,MARUTI
1,2015,41000,Diesel,Manual,First,19.67,126.2,11623.750,CRETA 1.6 CRDI SX OPTION,HYUNDAI
2,2011,46000,Petrol,Manual,First,18.2,88.7,4184.550,JAZZ V,HONDA
3,2012,87000,Diesel,Manual,First,20.77,88.76,5579.400,ERTIGA VDI,MARUTI
4,2013,40670,Diesel,Automatic,Second,15.2,140.8,16496.426,A4 NEW 2.0 TDI MULTITRONIC,AUDI

In [35]:
data["Mileage"] = pd.to_numeric(data["Mileage"], errors='coerce')
data["Power"] = pd.to_numeric(data["Power"], errors='coerce')
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 6019 entries, 0 to 6018
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Year               6019 non-null   int64
 1   Kilometers_Driven  6019 non-null   int64
 2   Fuel_Type          6019 non-null   str
 3   Transmission       6019 non-null   str
 4   Owner_Type         6019 non-null   str
 5   Mileage            6017 non-null   float64
 6   Power              5876 non-null   float64
 7   Price              6019 non-null   float64
 8   Model              6019 non-null   object
 9   Brand              6019 non-null   object
dtypes: float64(3), int64(2), object(2), str(3)
memory usage: 470.4+ KB

In [36]:
data["Power"] = data["Power"].fillna(data["Power"].median(), inplace=True)
data["Mileage"] = data["Mileage"].fillna(data["Mileage"].median(), inplace=True)
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 6019 entries, 0 to 6018
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Year               6019 non-null   int64
 1   Kilometers_Driven  6019 non-null   int64
 2   Fuel_Type          6019 non-null   str
 3   Transmission       6019 non-null   str
 4   Owner_Type         6019 non-null   str
 5   Mileage            6019 non-null   float64
 6   Power              6019 non-null   float64
 7   Price              6019 non-null   float64
 8   Model              6019 non-null   object
 9   Brand              6019 non-null   object
dtypes: float64(3), int64(2), object(2), str(3)
memory usage: 470.4+ KB

C:\Users\matthieu.catteyfaye\AppData\Local\Temp\ipykernel_6252\2332407880.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  data["Power"] = data["Power"].fillna(data["Power"].median(), inplace=True)
C:\Users\matthieu.catteyfaye\AppData\Local\Temp\ipykernel_6252\2332407880.py:2: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  data["Mileage"] = data["Mileage"].fillna(data["Mileage"].median(), inplace=True)

In [12]:
# Fonction pour visualiser les outliers : 
def iqr(data, col_name):
    q1 = data[col_name].quantile(0.25)
    q3 = data[col_name].quantile(0.75)
    iqr_ = q3 - q1

    upper_lim = q3 + 1.5*iqr_
    lower_lim = q1 - 1.5*iqr_

    outliers_above = data[data[col_name]>upper_lim]
    outliers_below = data[data[col_name]<lower_lim]

    print("\n", col_name, ":")

    print("Outliers above :",outliers_above[col_name].count())
    print("Outliers below :",outliers_below[col_name].count())

In [13]:
for col in data[["Kilometers_Driven", "Mileage", "Power"]].columns:
    iqr(data, col)

 Kilometers_Driven :
Outliers above : 202
Outliers below : 0

 Mileage :
Outliers above : 14
Outliers below : 68

 Power :
Outliers above : 239
Outliers below : 0

In [14]:
# Fonction pour remplacer les outliers par la médiane : 
def replace_outliers_by_median(data, col_name):  
    q1 = data[col_name].quantile(0.25)
    q3 = data[col_name].quantile(0.75)
    iqr_ = q3 - q1

    upper_lim = q3 + 1.5*iqr_
    lower_lim = q1 - 1.5*iqr_

    median = data[col_name].median()

    data.loc[data[col_name]>upper_lim, col_name] = median
    data.loc[data[col_name]<lower_lim, col_name] = median

    return data

In [15]:
for col in data[["Kilometers_Driven", "Mileage", "Power"]].columns:
    replace_outliers_by_median(data, col)
    iqr(data, col)

 Kilometers_Driven :
Outliers above : 63
Outliers below : 0

 Mileage :
Outliers above : 0
Outliers below : 1

 Power :
Outliers above : 111
Outliers below : 0

In [16]:
data

,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Power,Price,Model,Brand
0,2010,72000,CNG,Manual,First,26.60,58.16,1.75,WAGON R LXI CNG,Maruti
1,2015,41000,Diesel,Manual,First,19.67,126.20,12.50,CRETA 1.6 CRDI SX OPTION,Hyundai
2,2011,46000,Petrol,Manual,First,18.20,88.70,4.50,JAZZ V,Honda
3,2012,87000,Diesel,Manual,First,20.77,88.76,6.00,ERTIGA VDI,Maruti
4,2013,40670,Diesel,Automatic,Second,15.20,140.80,17.74,A4 NEW 2.0 TDI MULTITRONIC,Audi
...,...,...,...,...,...,...,...,...,...,...
6014,2014,27365,Diesel,Manual,First,28.40,74.00,4.75,SWIFT VDI,Maruti
6015,2015,100000,Diesel,Manual,First,24.40,71.00,4.00,XCENT 1.1 CRDI S,Hyundai
6016,2012,55000,Diesel,Manual,Second,14.00,112.00,2.90,XYLO D4 BSIV,Mahindra
6017,2013,46000,Petrol,Manual,First,18.90,67.10,2.65,WAGON R VXI,Maruti
6018,2011,47000,Diesel,Manual,First,25.44,57.60,2.50,BEAT DIESEL,Chevrolet

In [37]:
data.to_csv("..\\data\\train_post_modif_median.csv", index=None)

In [ ]:
data_post_f_e = pd.read_csv("..\\data\\train_post_modif.csv")
data_post_f_e.info()

<class 'pandas.DataFrame'>
RangeIndex: 6019 entries, 0 to 6018
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Year               6019 non-null   int64
 1   Kilometers_Driven  6019 non-null   int64
 2   Fuel_Type          6019 non-null   str
 3   Transmission       6019 non-null   str
 4   Owner_Type         6019 non-null   str
 5   Mileage            6019 non-null   float64
 6   Power              6019 non-null   float64
 7   Price              6019 non-null   float64
 8   Model              6019 non-null   str
 9   Brand              6019 non-null   str
dtypes: float64(3), int64(2), str(5)
memory usage: 470.4 KB

In [6]:
data = pd.read_csv('..\\data\\train.csv')
data["Model"] = data["Name"].str.split()
data["Brand"] = data["Model"].str[0]
data["Model"] = data["Model"].str[1:]
data["Model"] = data["Model"].str.join(' ')
data = data.drop(["Name", "Location", "New_Price"], axis=1)
data.head()

,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,Price,Model,Brand
0,2010,72000,CNG,Manual,First,26.6 km/kg,998 CC,58.16 bhp,5.0,1.75,Wagon R LXI CNG,Maruti
1,2015,41000,Diesel,Manual,First,19.67 kmpl,1582 CC,126.2 bhp,5.0,12.50,Creta 1.6 CRDi SX Option,Hyundai
2,2011,46000,Petrol,Manual,First,18.2 kmpl,1199 CC,88.7 bhp,5.0,4.50,Jazz V,Honda
3,2012,87000,Diesel,Manual,First,20.77 kmpl,1248 CC,88.76 bhp,7.0,6.00,Ertiga VDI,Maruti
4,2013,40670,Diesel,Automatic,Second,15.2 kmpl,1968 CC,140.8 bhp,5.0,17.74,A4 New 2.0 TDI Multitronic,Audi

In [ ]:
data["Mileage"] = data["Mileage"].str.split()
data["Mileage"] = data["Mileage"].str[0]
data["Power"] = data["Power"].str.split()
data["Power"] = data["Power"].str[0]
data["Engine"] = data["Engine"].str.split()
data["Engine"] = data["Engine"].str[0]
data.head()

,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,Price,Model,Brand
0,2010,72000,CNG,Manual,First,26.6,998,58.16,5.0,1.75,Wagon R LXI CNG,Maruti
1,2015,41000,Diesel,Manual,First,19.67,1582,126.2,5.0,12.50,Creta 1.6 CRDi SX Option,Hyundai
2,2011,46000,Petrol,Manual,First,18.2,1199,88.7,5.0,4.50,Jazz V,Honda
3,2012,87000,Diesel,Manual,First,20.77,1248,88.76,7.0,6.00,Ertiga VDI,Maruti
4,2013,40670,Diesel,Automatic,Second,15.2,1968,140.8,5.0,17.74,A4 New 2.0 TDI Multitronic,Audi

In [8]:
data["Brand"] = data["Brand"].str.upper()
data["Model"] = data["Model"].str.upper()
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 6019 entries, 0 to 6018
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Year               6019 non-null   int64
 1   Kilometers_Driven  6019 non-null   int64
 2   Fuel_Type          6019 non-null   str
 3   Transmission       6019 non-null   str
 4   Owner_Type         6019 non-null   str
 5   Mileage            6017 non-null   object
 6   Engine             5983 non-null   object
 7   Power              5983 non-null   object
 8   Seats              5977 non-null   float64
 9   Price              6019 non-null   float64
 10  Model              6019 non-null   object
 11  Brand              6019 non-null   object
dtypes: float64(2), int64(2), object(5), str(3)
memory usage: 564.4+ KB

In [9]:
data["Mileage"] = pd.to_numeric(data["Mileage"], errors='coerce')
data["Engine"] = pd.to_numeric(data["Engine"], errors='coerce')
data["Power"] = pd.to_numeric(data["Power"], errors='coerce')
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 6019 entries, 0 to 6018
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Year               6019 non-null   int64
 1   Kilometers_Driven  6019 non-null   int64
 2   Fuel_Type          6019 non-null   str
 3   Transmission       6019 non-null   str
 4   Owner_Type         6019 non-null   str
 5   Mileage            6017 non-null   float64
 6   Engine             5983 non-null   float64
 7   Power              5876 non-null   float64
 8   Seats              5977 non-null   float64
 9   Price              6019 non-null   float64
 10  Model              6019 non-null   object
 11  Brand              6019 non-null   object
dtypes: float64(5), int64(2), object(2), str(3)
memory usage: 564.4+ KB

In [11]:
data["Power"] = data["Power"].fillna(data["Power"].median(), inplace=True)
data["Mileage"] = data["Mileage"].fillna(data["Mileage"].median(), inplace=True)
data["Engine"] = data["Engine"].fillna(data["Engine"].median(), inplace=True)
data["Seats"] = data["Seats"].fillna(data["Seats"].median(), inplace=True)

data.info()

<class 'pandas.DataFrame'>
RangeIndex: 6019 entries, 0 to 6018
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Year               6019 non-null   int64
 1   Kilometers_Driven  6019 non-null   int64
 2   Fuel_Type          6019 non-null   str
 3   Transmission       6019 non-null   str
 4   Owner_Type         6019 non-null   str
 5   Mileage            6019 non-null   float64
 6   Engine             6019 non-null   float64
 7   Power              6019 non-null   float64
 8   Seats              6019 non-null   float64
 9   Price              6019 non-null   float64
 10  Model              6019 non-null   object
 11  Brand              6019 non-null   object
dtypes: float64(5), int64(2), object(2), str(3)
memory usage: 564.4+ KB

C:\Users\matthieu.catteyfaye\AppData\Local\Temp\ipykernel_8348\44862054.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  data["Power"] = data["Power"].fillna(data["Power"].median(), inplace=True)
C:\Users\matthieu.catteyfaye\AppData\Local\Temp\ipykernel_8348\44862054.py:2: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  data["Mileage"] = data["Mileage"].fillna(data["Mileage"].median(), inplace=True)
C:\Users\matthieu.catteyfaye\AppData\Local\Temp\ipykernel_8348\44862054.py:3: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  data["Engine"] = data["Engine"].fillna(data["Engine"].median(), inplace=True)
C:\Users\matthieu.catteyfaye\AppData\Local\Temp\ipykernel_8348\44862054.py:4: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  data["Seats"] = data["Seats"].fillna(data["Seats"].median(), inplace=True)

In [12]:
data.to_csv("..\\data\\data_more_features.csv", index=None)

In [2]:
data = pd.read_csv("..\\data\\data_more_features.csv")
data.head()

,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,Price,Model,Brand
0,2010,72000,CNG,Manual,First,26.60,998.0,58.16,5.0,1.75,WAGON R LXI CNG,MARUTI
1,2015,41000,Diesel,Manual,First,19.67,1582.0,126.20,5.0,12.50,CRETA 1.6 CRDI SX OPTION,HYUNDAI
2,2011,46000,Petrol,Manual,First,18.20,1199.0,88.70,5.0,4.50,JAZZ V,HONDA
3,2012,87000,Diesel,Manual,First,20.77,1248.0,88.76,7.0,6.00,ERTIGA VDI,MARUTI
4,2013,40670,Diesel,Automatic,Second,15.20,1968.0,140.80,5.0,17.74,A4 NEW 2.0 TDI MULTITRONIC,AUDI

In [3]:
data["Price"] = data["Price"]*929.9
data.head()

,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,Price,Model,Brand
0,2010,72000,CNG,Manual,First,26.60,998.0,58.16,5.0,1627.325,WAGON R LXI CNG,MARUTI
1,2015,41000,Diesel,Manual,First,19.67,1582.0,126.20,5.0,11623.750,CRETA 1.6 CRDI SX OPTION,HYUNDAI
2,2011,46000,Petrol,Manual,First,18.20,1199.0,88.70,5.0,4184.550,JAZZ V,HONDA
3,2012,87000,Diesel,Manual,First,20.77,1248.0,88.76,7.0,5579.400,ERTIGA VDI,MARUTI
4,2013,40670,Diesel,Automatic,Second,15.20,1968.0,140.80,5.0,16496.426,A4 NEW 2.0 TDI MULTITRONIC,AUDI

In [4]:
data.to_csv("..\\data\\data_more_features.csv", index=None)

In [5]:
data

,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,Price,Model,Brand
0,2010,72000,CNG,Manual,First,26.60,998.0,58.16,5.0,1627.325,WAGON R LXI CNG,MARUTI
1,2015,41000,Diesel,Manual,First,19.67,1582.0,126.20,5.0,11623.750,CRETA 1.6 CRDI SX OPTION,HYUNDAI
2,2011,46000,Petrol,Manual,First,18.20,1199.0,88.70,5.0,4184.550,JAZZ V,HONDA
3,2012,87000,Diesel,Manual,First,20.77,1248.0,88.76,7.0,5579.400,ERTIGA VDI,MARUTI
4,2013,40670,Diesel,Automatic,Second,15.20,1968.0,140.80,5.0,16496.426,A4 NEW 2.0 TDI MULTITRONIC,AUDI
...,...,...,...,...,...,...,...,...,...,...,...,...
6014,2014,27365,Diesel,Manual,First,28.40,1248.0,74.00,5.0,4417.025,SWIFT VDI,MARUTI
6015,2015,100000,Diesel,Manual,First,24.40,1120.0,71.00,5.0,3719.600,XCENT 1.1 CRDI S,HYUNDAI
6016,2012,55000,Diesel,Manual,Second,14.00,2498.0,112.00,8.0,2696.710,XYLO D4 BSIV,MAHINDRA
6017,2013,46000,Petrol,Manual,First,18.90,998.0,67.10,5.0,2464.235,WAGON R VXI,MARUTI
6018,2011,47000,Diesel,Manual,First,25.44,936.0,57.60,5.0,2324.750,BEAT DIESEL,CHEVROLET