In [104]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split    # Train/test split
from sklearn.pipeline import Pipeline                  # Pipeline to prevent leakage
from sklearn.compose import ColumnTransformer        # Different preprocessing per column type
from sklearn.preprocessing import  RobustScaler, OneHotEncoder
from sklearn.impute import SimpleImputer
from sklearn.linear_model import LinearRegression  , Lasso 
from sklearn.dummy import DummyRegressor
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error, root_mean_squared_error
from sklearn.svm import SVR

In [85]:
df=pd.read_csv(r"data\ priceinr.csv", sep=(","))
df

,Unnamed: 0,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Power,Price,brand,model,Engine
0,0,2010,72000,CNG,Manual,First,26.60,26.60,1.75,MARUTI,WAGON R,998.0
1,1,2015,41000,Diesel,Manual,First,19.67,19.67,12.50,HYUNDAI,CRETA 1.6,1582.0
2,2,2011,46000,Petrol,Manual,First,18.20,18.20,4.50,HONDA,JAZZ V,1199.0
3,3,2012,87000,Diesel,Manual,First,20.77,20.77,6.00,MARUTI,ERTIGA VDI,1248.0
4,4,2013,40670,Diesel,Automatic,Second,15.20,15.20,17.74,AUDI,A4 NEW,1968.0
...,...,...,...,...,...,...,...,...,...,...,...,...
5978,6014,2014,27365,Diesel,Manual,First,28.40,28.40,4.75,MARUTI,SWIFT VDI,1248.0
5979,6015,2015,100000,Diesel,Manual,First,24.40,24.40,4.00,HYUNDAI,XCENT 1.1,1120.0
5980,6016,2012,55000,Diesel,Manual,Second,14.00,14.00,2.90,MAHINDRA,XYLO D4,2498.0
5981,6017,2013,46000,Petrol,Manual,First,18.90,18.90,2.65,MARUTI,WAGON R,998.0
5982,6018,2011,47000,Diesel,Manual,First,25.44,25.44,2.50,CHEVROLET,BEAT DIESEL,936.0

In [86]:
df.Power.isnull().sum()

np.int64(2)

In [87]:

df["Power"] = df["Power"].replace(["null", "NaN", "-", "unknown"], np.nan)

In [88]:
df.dropna(subset=["Power"])

,Unnamed: 0,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Power,Price,brand,model,Engine
0,0,2010,72000,CNG,Manual,First,26.60,26.60,1.75,MARUTI,WAGON R,998.0
1,1,2015,41000,Diesel,Manual,First,19.67,19.67,12.50,HYUNDAI,CRETA 1.6,1582.0
2,2,2011,46000,Petrol,Manual,First,18.20,18.20,4.50,HONDA,JAZZ V,1199.0
3,3,2012,87000,Diesel,Manual,First,20.77,20.77,6.00,MARUTI,ERTIGA VDI,1248.0
4,4,2013,40670,Diesel,Automatic,Second,15.20,15.20,17.74,AUDI,A4 NEW,1968.0
...,...,...,...,...,...,...,...,...,...,...,...,...
5978,6014,2014,27365,Diesel,Manual,First,28.40,28.40,4.75,MARUTI,SWIFT VDI,1248.0
5979,6015,2015,100000,Diesel,Manual,First,24.40,24.40,4.00,HYUNDAI,XCENT 1.1,1120.0
5980,6016,2012,55000,Diesel,Manual,Second,14.00,14.00,2.90,MAHINDRA,XYLO D4,2498.0
5981,6017,2013,46000,Petrol,Manual,First,18.90,18.90,2.65,MARUTI,WAGON R,998.0
5982,6018,2011,47000,Diesel,Manual,First,25.44,25.44,2.50,CHEVROLET,BEAT DIESEL,936.0

In [89]:
df.dropna(subset=["Power"], inplace=True)

In [90]:
df.Power.isna().sum()

np.int64(0)

In [91]:
df["brand"].value_counts()

brand
MARUTI           1200
HYUNDAI          1100
HONDA             602
TOYOTA            409
MERCEDES-BENZ     318
VOLKSWAGEN        315
FORD              300
MAHINDRA          271
BMW               262
AUDI              236
TATA              186
SKODA             173
RENAULT           145
CHEVROLET         121
NISSAN             91
LAND               57
JAGUAR             40
MITSUBISHI         27
MINI               26
FIAT               25
VOLVO              21
PORSCHE            18
JEEP               15
DATSUN             13
ISUZU               3
FORCE               3
SMART               1
AMBASSADOR          1
BENTLEY             1
LAMBORGHINI         1
Name: count, dtype: int64

In [92]:
df.info()

<class 'pandas.DataFrame'>
Index: 5981 entries, 0 to 5982
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Unnamed: 0         5981 non-null   int64
 1   Year               5981 non-null   int64
 2   Kilometers_Driven  5981 non-null   int64
 3   Fuel_Type          5981 non-null   str
 4   Transmission       5981 non-null   str
 5   Owner_Type         5981 non-null   str
 6   Mileage            5981 non-null   float64
 7   Power              5981 non-null   float64
 8   Price              5981 non-null   float64
 9   brand              5981 non-null   str
 10  model              5981 non-null   str
 11  Engine             5981 non-null   float64
dtypes: float64(4), int64(3), str(5)
memory usage: 607.4 KB

In [93]:
x=df.drop(columns=["Price"])
y=df["Price"]

In [94]:
numeric_features = x.select_dtypes(include=[np.number]).columns.tolist()   # Numeric columns list.tolist()  
categorical_features = x.select_dtypes(exclude=[np.number]).columns.tolist()

In [95]:
numeric_features

['Unnamed: 0', 'Year', 'Kilometers_Driven', 'Mileage', 'Power', 'Engine ']

In [96]:
categorical_features

['Fuel_Type', 'Transmission', 'Owner_Type', 'brand', 'model']

In [97]:
#convertit des données nominales aux valeurs numériques 1 2 3 4 5
# df["Fuel_Type"]=pd.factorize(df["Fuel_Type"])[0]
# df["Transmission"]=pd.factorize(df["Transmission"])[0]
# df["Owner_Type"]=pd.factorize(df["Owner_Type"])[0]
# df["Brand"]=pd.factorize(df["Brand"])[0]
# df["Model"]=pd.factorize(df["Model"])[0]
# df
#df = pd.get_dummies(df, columns=["Transmission", "Owner_Type", "Model","Brand"], dtype=float)

In [98]:
# df= df.drop(["Fuel_Type"], axis=1)
# df

In [99]:

# Séparer x et y
x = df.drop(columns=["Price"])
y = df["Price"]

# Colonnes
numeric_features = x.select_dtypes(include=[np.number]).columns.tolist()
categorical_features = x.select_dtypes(exclude=[np.number]).columns.tolist()

# Transformations
numeric_transformer = Pipeline(steps=[
    ("scaler", RobustScaler())
])

categorical_transformer = Pipeline(steps=[
    ("encoder", OneHotEncoder(drop="first", handle_unknown="ignore"))
])

# Preprocess
preprocess = ColumnTransformer(
    transformers=[
        ("numerique", numeric_transformer, numeric_features),
        ("categorial", categorical_transformer, categorical_features)
    ]
)

# Pipeline complet
model = Pipeline(steps=[
    ("preprocess", preprocess),
    ("regressor", LinearRegression())
])

# Split
x_train, x_test, y_train, y_test = train_test_split( x, y, test_size=0.2, random_state=42)
print(x_train.shape , x_test.shape) 
# Entraînement
model.fit(x_train, y_train)

(4784, 11) (1197, 11)

Pipeline(steps=[('preprocess',
                 ColumnTransformer(transformers=[('numerique',
                                                  Pipeline(steps=[('scaler',
                                                                   RobustScaler())]),
                                                  ['Unnamed: 0', 'Year',
                                                   'Kilometers_Driven',
                                                   'Mileage', 'Power',
                                                   'Engine ']),
                                                 ('categorial',
                                                  Pipeline(steps=[('encoder',
                                                                   OneHotEncoder(drop='first',
                                                                                 handle_unknown='ignore'))]),
                                                  ['Fuel_Type', 'Transmission',
                                                   'Owner_Type', 'brand',
                                                   'model'])])),
                ('regressor', LinearRegression())])

In [100]:
y_pred = model.predict(x_test)
mse=mean_squared_error(y_test, y_pred)
rmse=root_mean_squared_error(y_test , y_pred)
mae=mean_absolute_error(y_test, y_pred)
r2=r2_score(y_test , y_pred)

print(f"MSE  : {mse:.2f}")
print(f"RMSE : {rmse:.2f}")
print(f"MAE  : {mae:.2f}")
print(f"R²   : {r2:.4f}")

MSE  : 18.25
RMSE : 4.27
MAE  : 2.31
R²   : 0.8491

c:\Users\samya.taqi\Desktop\SAMYA TAQI\Pr-dire-le-prix-de-voiture--projet-r-gression\price_car\pricecarenv\Lib\site-packages\sklearn\preprocessing\_encoders.py:261: UserWarning: Found unknown categories in columns [3, 4] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(msg, UserWarning)

In [102]:

# Séparer x et y
x = df.drop(columns=["Price"])
y = df["Price"]

# Colonnes
numeric_features = x.select_dtypes(include=[np.number]).columns.tolist()
categorical_features = x.select_dtypes(exclude=[np.number]).columns.tolist()

# Transformations
numeric_transformer = Pipeline(steps=[
    ("scaler", RobustScaler())
])

categorical_transformer = Pipeline(steps=[
    ("encoder", OneHotEncoder(drop="first", handle_unknown="ignore"))
])

# Preprocess
preprocess = ColumnTransformer(
    transformers=[
        ("numerique", numeric_transformer, numeric_features),
        ("categorial", categorical_transformer, categorical_features)
    ]
)

# Pipeline complet
model = Pipeline(steps=[
    ("preprocess", preprocess),
    ("regressor", Lasso(alpha=0.1))
])

# Split
x_train, x_test, y_train, y_test = train_test_split( x, y, test_size=0.2, random_state=42)
print(x_train.shape , x_test.shape) 
# Entraînement
model.fit(x_train, y_train)

(4784, 11) (1197, 11)

Pipeline(steps=[('preprocess',
                 ColumnTransformer(transformers=[('numerique',
                                                  Pipeline(steps=[('scaler',
                                                                   RobustScaler())]),
                                                  ['Unnamed: 0', 'Year',
                                                   'Kilometers_Driven',
                                                   'Mileage', 'Power',
                                                   'Engine ']),
                                                 ('categorial',
                                                  Pipeline(steps=[('encoder',
                                                                   OneHotEncoder(drop='first',
                                                                                 handle_unknown='ignore'))]),
                                                  ['Fuel_Type', 'Transmission',
                                                   'Owner_Type', 'brand',
                                                   'model'])])),
                ('regressor', Lasso(alpha=0.1))])

In [103]:
# Faire des prédictions
y_pred = model.predict(x_test)

# Évaluer
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print(f"MSE = {mse:.2f}")
print(f"R²  = {r2:.2f}")

MSE = 38.81
R²  = 0.68

c:\Users\samya.taqi\Desktop\SAMYA TAQI\Pr-dire-le-prix-de-voiture--projet-r-gression\price_car\pricecarenv\Lib\site-packages\sklearn\preprocessing\_encoders.py:261: UserWarning: Found unknown categories in columns [3, 4] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(msg, UserWarning)

In [110]:
# Séparer x et y
x = df.drop(columns=["Price"])
y = df["Price"]

# Colonnes
numeric_features = x.select_dtypes(include=[np.number]).columns.tolist()
categorical_features = x.select_dtypes(exclude=[np.number]).columns.tolist()

# Transformations
numeric_transformer = Pipeline(steps=[
    ("scaler", RobustScaler())
])

categorical_transformer = Pipeline(steps=[
    ("encoder", OneHotEncoder(drop="first", handle_unknown="ignore"))
])

# Preprocess
preprocess = ColumnTransformer(
    transformers=[
        ("numerique", numeric_transformer, numeric_features),
        ("categorial", categorical_transformer, categorical_features)
    ]
)


model = Pipeline(steps=[
    ("preprocess", preprocess),
    ("svm", SVR(kernel="rbf", C=1.0, epsilon=0.1))
])

# Split
x_train, x_test, y_train, y_test = train_test_split( x, y, test_size=0.2, random_state=42)
print(x_train.shape , x_test.shape) 
# Entraînement
model.fit(x_train, y_train)

(4784, 11) (1197, 11)

Pipeline(steps=[('preprocess',
                 ColumnTransformer(transformers=[('numerique',
                                                  Pipeline(steps=[('scaler',
                                                                   RobustScaler())]),
                                                  ['Unnamed: 0', 'Year',
                                                   'Kilometers_Driven',
                                                   'Mileage', 'Power',
                                                   'Engine ']),
                                                 ('categorial',
                                                  Pipeline(steps=[('encoder',
                                                                   OneHotEncoder(drop='first',
                                                                                 handle_unknown='ignore'))]),
                                                  ['Fuel_Type', 'Transmission',
                                                   'Owner_Type', 'brand',
                                                   'model'])])),
                ('svm', SVR())])

In [111]:
y_pred=model.predict(x_test)
# Évaluer
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print(f"MSE = {mse:.2f}")
print(f"R²  = {r2:.2f}")

MSE = 29.15
R²  = 0.76

c:\Users\samya.taqi\Desktop\SAMYA TAQI\Pr-dire-le-prix-de-voiture--projet-r-gression\price_car\pricecarenv\Lib\site-packages\sklearn\preprocessing\_encoders.py:261: UserWarning: Found unknown categories in columns [3, 4] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(msg, UserWarning)